spring:
  config:
    activate:
      on-profile: "qa"
build:
  version: "2.0"

accounts:
  message: "Welcome to EazyBank accounts related QA APIs "
  contactDetails:
    name: "Shivam Dixit - QA Lead"
    email: "shivam007mrt@gmail.com"
  onCallSupport:
    - 8445620377
    - 9368005699