server:
  port: 8071

spring:
  application:
    name: "configserver"

  profiles:
#    active: native
    active: git
  cloud:
    config:
      server:
#        native:
#          search-locations: "classpath:/config"
#          search-locations: "file:///D://Development//MicroServices//config_filesystem"
        git:
          uri: "https://github.com/Shivam304sharma/eazybank-config.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true
encrypt:
  key: "YI76W9gMqCvBFEC4Swggb3E2duk65jKK"