services:
  accounts:
    image: "shivamdixit07/accounts:s4"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - shivamdixit07
  loans:
    image: "shivamdixit07/loans:s4"
    container_name: loans-ms
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - shivamdixit07
  cards:
    image: "shivamdixit07/cards:s4"
    container_name: cards-ms
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - shivamdixit07
networks:
  shivamdixit07:
    driver: bridge
